# ========================================
# Service Account
# ========================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: cannaai
  namespace: cannaai-production
  labels:
    app: cannaai
automountServiceAccountToken: false
